### ISSUE TITLE
test

### ISSUE THREAD

**Issue by 13shayan82** [Amirmohamadhejazi/tst#3]
01010

**Comment by Amirmohamadhejazi** [comment]
this bug has go to readme file and paste it

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      body {
      padding: 25px;
      background-color: red;
      color: black;
      font-size: 25px;
      transition:1s;
      }
      .dark-mode {
       background-color: black;
       color: white;
       transition:1s;
       }
    </style>
  </head>
<body>
<button onclick="myFunction()">Toggle dark mode</button>
    <script>
      function myFunction() {
        var element = document.body;
        element.classList.toggle("dark-mode");
      }
    </script>
  </body>
</html>
